Testing new db-servers.
Skatteetaten/dbh pull request #55
Opened 2020-10-29 14:56 UTC by stromland

2020-10-29 22:59 UTC, bentsolheim requested changes

2020-10-29 22:59 UTC, bentsolheim commented on src/test/kotlin/no/skatteetaten/aurora/databasehotel/utils/OracleSchemaDeleter.kt
> +                // See test/resources/kill_dev_session.sql
Denne filen ser ikke ut til å eksistere?

2020-11-12 14:19 UTC, stromland commented on src/test/kotlin/no/skatteetaten/aurora/databasehotel/utils/OracleSchemaDeleter.kt
> +                // See test/resources/kill_dev_session.sql
Har pushet den nå

2020-11-13 12:38 UTC, bentsolheim approved these changes

2020-11-17 09:23 UTC, merged